### ISSUE TITLE
Module GoogleImageScrapper not found

### ISSUE THREAD

**Issue by CloneHub94** [ohyicong/Google-Image-Scraper#1]
![image](https://user-images.githubusercontent.com/37849398/92599190-2fe32980-f2aa-11ea-807c-d42fd3078783.png)

I keep on getting an error when I wanna run Google image scrapper. It doesn't find the module. Even though I've installed Selenium, google chrome, and the latest driver for windows(See image I uploaded). Does anyone know what I should do?

**Comment by ohyicong** [comment]
Please clone the entire repository. You must put GoogleImageScapper.py in the same folder.

**Comment by CloneHub94** [comment]
In the same folder as foldeerr_createion.py?

**Comment by ohyicong** [comment]
yes my friend
