### ISSUE TITLE
It is possible search using a local image as input instead of a string?

### ISSUE THREAD

**Issue by Nykodemus** [ohyicong/Google-Image-Scraper#10]
I am wondering if there is a way to work the script in order to search images of a bigger size than images already on the local disk, inputting those local images as "search_key".

**Comment by ohyicong** [comment]
You are able to filter the search by specifying the min and max resolution

**Comment by Nykodemus** [comment]
@ohyicong I understand that, but there is a way of upload an image from the disk instead of a search string, in order for the scraper search that specific image, i.e., a picture of Monalisa?
