### ISSUE TITLE
stuck on consent page

### ISSUE THREAD

**Issue by UnlondonGR** [ohyicong/Google-Image-Scraper#26]
It was working fine 2 days ago and now it gets stuck at consent.google.com page and gets stuck at "[INFO] Unable to get link"
when i press accept all on the consent page it doesnt save and i wanna be able to put it on headless mode and not have to click on accept all all the time.
anyway to skip the page?

only thing i changed about the code was the terms it was searching for (thats not the problem tho)

edit: using chrome 103 with the corresponding chromedriver

**Comment by ohyicong** [comment]
What is your search term?

**Comment by UnlondonGR** [comment]
search terms are ["Cat","Pigeon"] but I also tried like this: ['Cat','Pigeon'] but it was the same error

**Comment by ohyicong** [comment]
Interesting, I don't have this showing up on my screen. So I cannot rectify this problem.

**Comment by ohyicong** [comment]
I am using version 103 too. If this issue surfaces on my computer, I will give this program a fix.

**Comment by bjuncek** [comment]
I'd like to re-raise this as this shows up in the headless mode on an un-signed in chrome on linux.
