### ISSUE TITLE
Unable to get link

### ISSUE THREAD

**Issue by csmit86** [ohyicong/Google-Image-Scraper#29]
When headless is True the script is unable to bypass the license agreement pop-up in chrome.
When headless is False I can accept it manually and the script continues to get links but does not download the images into the folder.

**Comment by csmit86** [comment]
Ah, I just realize it downloads the images after all the links are obtained.

**Comment by ItsGoldeneyes** [comment]
> Ah, I just realize it downloads the images after all the links are obtained.

You got it, what license agreement popup are you referring to? Is this something that's an issue or did you find a solution?

**Comment by csmit86** [comment]
Like when you use Chrome in Incognito mode, and google something, you get a pop-up asking to agree to google's terms. The only way I managed to bypass it is by running the script with headless = false and decline the agreement manually. But then I can't use my pc while the script is running. It stops when I minimise the browser.

**Comment by ItsGoldeneyes** [comment]
> Like when you use Chrome in Incognito mode, and google something, you get a pop-up asking to agree to google's terms. The only way I managed to bypass it is by running the script with headless = false and decline the agreement manually. But then I can't use my pc while the script is running. It stops when I minimise the browser.

I've never seen that popup before, could be a region issue. What country are you in?

**Comment by csmit86** [comment]
The Netherlands

**Comment by ohyicong** [comment]
I suspect it may be a regional issue. I'm unable to replicate this issue.

**Comment by ohyicong** [comment]
I think you might be able to load your chrome profile into selenium to resolve this issue

**Comment by mooujarrar** [comment]
Hi, 

In the function GoogleImageScraper after the line
`driver.get("https://www.google.com")`
you can add: 
`driver.find_element(By.ID, "L2AGLb").click()`

That should bypass the chrome popup by clicking on the Accept all button.
I will push that fix if you confirm that it works for you.

**Comment by meron1122** [comment]
@mooujarrar  It works :)

**Comment by muhammad-mobeen** [comment]
The popup usually occurs while trying to search flagged or age-restricted content; hence, Google asks for the agreement.
Good thing @mooujarrar solved it.

**Comment by juanla** [comment]
> 

Works for me too, thanks.

**Comment by Jan-Oliver** [comment]
FYI: 
The method mentioned above didn't work for me, as the screen went from a "Accept all" popup into a whole "Accept all" screen. I thus had to add
```python
def find_image_urls(self):
        """
            This function search and return a list of image urls based on the search key.
            Example:
                google_image_scraper = GoogleImageScraper("webdriver_path","image_path","search_key",number_of_photos)
                image_urls = google_image_scraper.find_image_urls()

        """
        print("[INFO] Gathering image links")
        self.driver.get(self.url)
        ...
        accept_all_button_xpath = '//*[@id="yDmH0d"]/c-wiz/div/div/div/div[2]/div[1]/div[3]/div[1]/div[1]/form[2]/div/div/button'
        self.driver.find_element_by_xpath(accept_all_button_xpath).click()
```
I hope this helps somebody!
