### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by Mohamad-Jaallouk** [ohyicong/Google-Image-Scraper#32]
It work on windows. But when I run it on linux I get a loop:

`[INFO] installing new chromedriver
[INFO] downloading chromedriver ver: 107.0.5304.62: https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip
[INFO] lastest chromedriver downloaded
[INFO] installing new chromedriver
[INFO] downloading chromedriver ver: 107.0.5304.62: https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip
[INFO] lastest chromedriver downloaded
[INFO] installing new chromedriver
[INFO] downloading chromedriver ver: 107.0.5304.62: https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip
[INFO] lastest chromedriver downloaded
[INFO] installing new chromedriver
[INFO] downloading chromedriver ver: 107.0.5304.62: https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip
[INFO] lastest chromedriver downloaded`

**Comment by ohyicong** [comment]
Hello, this project doesn't support linux.
