### ISSUE TITLE
Program loops indefinitely while trying to install chrome driver

### ISSUE THREAD

**Issue by AColocho** [ohyicong/Google-Image-Scraper#36]
- Issue happens in MacOS.
- Keyword search = Billboard

**Comment by Januuus** [comment]
I have the same issue on Ubuntu 20.04

Create the image file correctly > infinite loop > ???

**Comment by ohyicong** [comment]
Hi, this project is not designed for linux system. Please use with windows PC instead.

**Comment by AColocho** [comment]
> Hi, this project is not designed for linux system. Please use with windows PC instead.

Any chance you can add this to your ReadMe? I think it would be helpful state that in requirements, so other developers can save time. I can create a PR updating the docs if you are busy.

**Comment by ohyicong** [comment]
Hi, thanks for highlighting. I have updated the readme to reflect the requirements.
