### ISSUE TITLE
[macOS] chromedriver can't launch - "unable to download lastest chromedriver. the system will use the local version instead"

### ISSUE THREAD

**Issue by nikolaydyankov** [ohyicong/Google-Image-Scraper#40]
Without modifying anything and running the `python3 main.py` from Terminal, I get this:

```
python3 main.py
[INFO] installing new chromedriver
[INFO] downloading chromedriver ver: 110.0.5481.77: https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_mac64.zip
[WARN] unable to download lastest chromedriver. the system will use the local version instead.
[INFO] installing new chromedriver
[INFO] downloading chromedriver ver: 110.0.5481.77: https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_mac64.zip
[WARN] unable to download lastest chromedriver. the system will use the local version instead.
```

I can see the Chrome icon bouncing in the dock, but then stopping, and it repeats again. Is this some permission issue?
Also I can see it downloaded webdriver/chromedriver and webdriver/chromedriver_mac64.zip

**Comment by Mic-N** [comment]
confirmed here as well, endless loop trying to patch.  Have tried on both win64 and linux (with chromium-chromedriver instralled)

**Comment by ohyicong** [comment]
Hi, I didn't test the code on linux/mac. So I can't verify that it is working for them.

**Comment by ohyicong** [comment]
Fixed on latest updated. Thanks for highlighting!

**Comment by usama-axcelerate** [comment]
It's still not working in linux (Ubuntu)
