### ISSUE TITLE
Not working and no error message

### ISSUE THREAD

**Issue by zarveyy** [ohyicong/Google-Image-Scraper#44]
Followed the readme step by step but nothing happens when I launch the script in my terminal, the folders are created and then nothing.

Env : Ubuntu 20.04.5 LTS running on WSL

**Comment by pors** [comment]
Same here on Mac OS, python 3.10.9, got this output for each image iteration:

`[INFO] Unable to get link`

**Comment by M0rbidSarcasm** [comment]
Reference to Unable to get link #33

Try these packages and version
selenium==3.141.0
requests==2.25.1
pillow==9.0.1

Every second image we tried to download showed unable to get link, after updating the packages it went a bit smoother and faster. Only every 50 images or so now go into an unable to get link loop :)

**Comment by rodrigo-barraza** [comment]
Even with the packages recommended, I'm getting the `[INFO] Unable to get link` loop since yesterday. And I noticed starting yesterday, only around 50 images would only download, regardless of the query.

**Comment by M0rbidSarcasm** [comment]
Okay so, what is the next step? Do we disable the automatic update of the chrome driver to use the latest, most stable chrome driver/version that doesn't use the "related image results" function? Or do we enable images to download from encrypted websites? Like Https?  Cuz after also playing with the code and using 360 image search keys we also have 50% accurate downloads. Especially with the search keys being more than 1 word for example "Phillips coffee machine and grinder". 

Please let me know because this has been driving me mad for months.

**Comment by ohyicong** [comment]
Hi, seems like the class tag used to identify the image link has changed, which resulted in this issue. I'm working on a fix now, will update everyone soon.

**Comment by ohyicong** [comment]
Patch has been released. It has been tested only on Windows OS, and may not work on others.

**Comment by rodrigo-barraza** [comment]
You're a life saver @ohyicong ! Thank you for your quick response time and amazing xpath skills. Let me know if there is anywhere I can go to buy you a coffee or whatever :)!

**Comment by M0rbidSarcasm** [comment]
@ohyicong our downloads are amazing now! No unable to get links, and the accuracy is amazing!!! Thank you so much, you genius!

**Comment by AmirSh15** [comment]
Thanks for your unwavering support, but I'm now facing another problem. Once I call the browser and approach Google, the 'Before you continue' pop-up window appears and won't let the remaining code run. Let me know if you know of any solution for it.

**Comment by ohyicong** [comment]
Hi @AmirSh15, this issue was highlighted by other users before, I wanted to fix it but I can't replicate the "pop-up" behavior on my computer. If you have a solution, I don't mind merging it into my repository. I will close this thread, as this is a separate issue. Thanks!

**Comment by AmirSh15** [comment]
Hi @ohyicong, I found the solution for the cookie pop-up window once google.com is called. It seems that in the new chrome version this window appears! You only need to add the below script after [this line of code](https://github.com/ohyicong/Google-Image-Scraper/blob/321219b28e3510108289fcd7ed29f66be3373cdd/GoogleImageScraper.py#L53).

`WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.ID, "W0wltc"))).click()`
