### ISSUE TITLE
Skip images whose urls start with "https://encrypted-tbn0.gstatic.com/" because we are not able to download them

### ISSUE THREAD

**Issue by GimChuang** [ohyicong/Google-Image-Scraper#9]
Hi, thanks for this helpful tool and the Youtube tutorial!
I am experiencing the same issue with #4 
It seems that we can't download images whose url starts with "https://encrypted-tbn0.gstatic.com/".
(It will say they are downloaded, but they aren't.)
So sometimes we request say 1000 images but only 5 are downloaded.
I found [this](https://stackoverflow.com/a/61982397) and modified the code in GoogleImageScraper.py line 103-104.
It now skips those images we are not able to download, which suits my needs.
```python
for image in images:
                    #only download images that starts with http
                    src = image.get_attribute("src")
                    if(src[:4].lower() in ["http"]) and not (src.startswith("https://encrypted-tbn0.gstatic.com/")):
                        print("[INFO] %d. %s"%(count,image.get_attribute("src")))
                        image_urls.append(image.get_attribute("src"))
                        count +=1
                        break
```

**Comment by JanithaChathuranga** [comment]
![Uploading 7a89fa60bd41d774443eb5b7f065be0f.jpg…]()
